import type { Metadata } from "next";
import { Public_Sans } from 'next/font/google'
import favico from "/public/assets/icons/logo.svg"
import PreHeader from "./shared-components/PreHeader";
import Header from "./shared-components/Header";
import MainNav from "./shared-components/MainNav";
import LoginModal from "./shared-components/LoginModal";
import { ToastContainer } from "react-toastify";

import 'react-toastify/dist/ReactToastify.css';
import 'swiper/css';
import "./globals.css";
import Footer from "./shared-components/Footer";
import ScrollTopBtn from "./shared-components/ScrollTopBtn";
import { AOSInit } from "./shared-components/Aos";


const font = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Techno Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ar">
        <head>
            <link rel="shortcut icon" href={favico.src} type="image/x-icon" />
        </head>
      <body className={font.className}>
        <PreHeader />
        <Header />
        <MainNav />
         {children}
         <Footer/>
         <ScrollTopBtn />
        <LoginModal/>
        <ToastContainer />
         <AOSInit/>
        </body>
    </html>
  );
}
